name: Frontend Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and run tests
      working-directory: ./client
      run: |
        docker build -f Dockerfile.test -t frontend-test .
        docker run --rm frontend-test
